### PR TITLE
Added text file documenting what needs to be done.

### PR DESCRIPTION
**Pull request by HFajardo**
Added PROGESS.txt with a to-do list of what needs to be done.

### CODE REVIEW

**Comment by kyledewey** [comment]
Review requested from @AnanDoh.

**Comment by kyledewey** [comment]
Additional review requested by @cooljohnny3

**Comment by cooljohnny3** [comment]
Some more detail on what you have learned about the code base would be nice.
For generating the unit and integration tests did you look at the tests folder to see what tests already exist?  It would be a good idea to see what is already being tested before writing your own tests.

**Review by AnanDoh — COMMENTED** [review]
Seems good. Understanding the codebase is a great step. You should make a mini-doc for the reviewers to understand as well.

**Review by cooljohnny3 — APPROVED** [review]
Some more detail on what you have learned about the code base would be nice.
For generating the unit and integration tests did you look at the tests folder to see what tests already exist? It would be a good idea to see what is already being tested before writing your own tests.

**Pull request merged**
